changelog:
  categories:
    - title: Breaking Changes
      labels:
        - semver:major
    - title: Features
      labels:
        - semver:minor
    - title: Fixes and Improvements
      labels:
        - semver:patch
    - title: Other Changes
      labels:
        - '*'
